[package]
name = "game-of-life"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
regex = "1"
once_cell = "1"
bitvec = "1.0.1"
rand = { version = "0.9.1", optional = true }

[features]
default = []
native = ["rand"]