name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WASM
        run: wasm-pack build --target web --out-dir pkg --release

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install TypeScript
        run: npm install --save-dev typescript
      
      - name: Compile TypeScript
        run: npx tsc
      
      - name: Prepare dist folder
        run: |
          rm -fr dist
          mkdir -p dist
          cp -r pkg dist/pkg
          cp index.html dist/
          cp -r js dist/js
          cp -r help dist/help
          cp -r css dist/css
          cp favicon.ico dist/
          rm dist/pkg/.gitignore 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
